---
name: Get Schemas

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pull-requests: write

env:
  URL_FORMAT: ${{ vars.URL_FORMAT || 'https://schema.cloudformation.${region}.amazonaws.com/CloudformationSchema.zip' }}

jobs:
  get-schemas:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4
      - id: download-schemas
        name: Download per-region CloudFormation schemas
        run: |
          regions=$(curl -s https://raw.githubusercontent.com/boto/botocore/develop/botocore/data/endpoints.json | jq -r '.partitions[].regions | keys[]')
          for region in $regions; do
            export region
            download_url=$(echo "${URL_FORMAT}" | envsubst)
            file=$(basename $download_url)
            curl -s -o ${region}.zip $download_url &> /dev/null
            if [[ -f "${region}.zip" ]]; then
              mkdir -p ./schemas/${region}
              unzip -q -o ${region}.zip -d ./schemas/${region} && rm -f ./schemas/${region}/${file}
            fi
          done
          unset region
      - id: commit
        name: Commit changes
        run: |
          git add .
          git commit -m "Update CloudFormation schemas"
          git push origin ${{ github.event.repository.default_branch }}
...